/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_darren_ndk12_NdkSimple1 */

#ifndef _Included_com_darren_ndk12_NdkSimple1
#define _Included_com_darren_ndk12_NdkSimple1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darren_ndk12_NdkSimple1
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_darren_ndk12_NdkSimple1_changeName
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_darren_ndk12_NdkSimple1_changeAge
(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_darren_ndk12_NdkSimple1_callAddMathod
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
