/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_east_NdkSample1 */

#ifndef _Included_com_east_NdkSample1
#define _Included_com_east_NdkSample1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_east_NdkSample1
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_east_NdkSample1_changeName
  (JNIEnv *, jobject);

/*
 * Class:     com_east_NdkSample1
 * Method:    changeAge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_east_NdkSample1_changeAge
  (JNIEnv *, jclass);

/*
 * Class:     com_east_NdkSample1
 * Method:    callAddMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_east_NdkSample1_callAddMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
