/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_east_NdkSample */
// 用来打一个标记， c 在编译的时候会把头文件 copy 到你引入的地方，不管是重复引用还是相互引用都只会 copy 一次
#ifndef _Included_com_east_NdkSample
#define _Included_com_east_NdkSample
#ifdef __cplusplus // 相当于 if 语句 c++
// 不管是 c 还是 c++ 统一都是采用 c 的编译方法，因为在 c 里面是不允许函数重载的，但是在 c++ 里面可以
extern "C" {
#endif
/*
 * Class:     com_east_NdkSample
 * Method:    getSingnaturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_east_NdkSample_getSingnaturePassword
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
