/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_east_jni08_Sample1 */

#ifndef _Included_com_east_jni08_Sample1
#define _Included_com_east_jni08_Sample1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_east_jni08_Sample1
 * Method:    createPoint
 * Signature: ()Lcom/east/jni08/Point;
 */
JNIEXPORT jobject JNICALL Java_com_east_jni08_Sample1_createPoint
  (JNIEnv *, jclass);

/*
 * Class:     com_east_jni08_Sample1
 * Method:    callStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_east_jni08_Sample1_callStaticMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
